name: Update DokuWiki

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the master branch
    paths:
      - 'data/cobblemon/spawn_pool_world/**'  # Only trigger when files in this directory change

  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  update-wiki:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Use the latest version of checkout action

    - name: Set up Python
      uses: actions/setup-python@v5  # Use the latest version of setup-python action
      with:
        python-version: '3.x'  # Use Python 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install dokuwikixmlrpc  # Install the necessary library for DokuWiki interaction

    - name: Run update script
      env:
        DOKUWIKI_API_URL: ${{ secrets.DOKUWIKI_API_URL }}  # DokuWiki API URL from secrets
        DOKUWIKI_USER: ${{ secrets.DOKUWIKI_USER }}  # DokuWiki username from secrets
        DOKUWIKI_PASSWORD: ${{ secrets.DOKUWIKI_PASSWORD }}  # DokuWiki password from secrets
      run: python update_wiki.py  # Run the Python script to update DokuWiki
