name: update_wiki

on:
  push:
    paths:
      - 'data/cobblemon/spawn_pool_world/**' # Trigger on changes in this directory
  workflow_dispatch: # Allow manual triggering

jobs:
  update_wiki_job:
    runs-on: ubuntu-latest
    env:
      DOKUWIKI_API_URL: ${{ secrets.DOKUWIKI_API_URL }}  # DokuWiki API URL from secrets
      DOKUWIKI_USER: ${{ secrets.DOKUWIKI_USER }}        # DokuWiki username from secrets
      DOKUWIKI_PASSWORD: ${{ secrets.DOKUWIKI_PASSWORD }} # DokuWiki password from secrets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Or your preferred Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dokuwikixmlrpc python-dotenv # Add other dependencies if needed by your script
          # If you have a requirements.txt file, you can use:
          # pip install -r requirements.txt

      - name: Run update script
        run: python update_wiki.py