name: Update DokuWiki Spawns

on:
  push:
    branches:
      - main # Or your default branch
    paths:
      - 'data/cobblemon/spawn_pool_world/**.json' # Trigger on changes in spawn files
      - 'pokedex_data.json' # Also trigger if pokedex data changes
      - '.github/workflows/update_wiki.yml' # Trigger if workflow itself changes
      - 'update_dokuwiki.py' # Trigger if script changes
  workflow_dispatch: # Allow manual triggering from the Actions tab

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use a recent Python 3 version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dokuwikixmlrpc requests # requests might be used by dokuwikixmlrpc

      - name: Run Wiki Update Script
        env:
          DOKUWIKI_URL: ${{ secrets.DOKUWIKI_URL }}
          DOKUWIKI_USER: ${{ secrets.DOKUWIKI_USER }}
          DOKUWIKI_PASSWORD: ${{ secrets.DOKUWIKI_PASSWORD }}
          COMMIT_HASH: ${{ github.sha }} # Pass the commit hash
        run: |
          python update_dokuwiki.py \
            --url "$DOKUWIKI_URL" \
            --user "$DOKUWIKI_USER" \
            --password "$DOKUWIKI_PASSWORD" \
            --pokedex-file "pokedex_data.json" \
            --spawn-dir "data/cobblemon/spawn_pool_world" \
            --namespace "mythsandlegends:datapack:spawn_pool_world" \
            --commit-hash "$COMMIT_HASH"